### PR TITLE
Fix small typo

### PR DESCRIPTION
**Pull request by pmukerji**
Came across while reading the project description:

`You?ll` => `You'll`

### CODE REVIEW

**Comment by davidsmandrade** [comment]
I had this problem: visuals.py", line 63
    print "'{}' is not a feature of the Titanic data. Did you spell something wrong?".format(key)
                                                                                    ^
SyntaxError: invalid syntax

**Comment by pmukerji** [comment]
Hi @davidsmandrade - did you run into that issue running the code from my PR? It seems unrelated somehow (I only edited a markdown file in the customer_segments project).

**Comment by arunkumarchacko** [comment]
@davidsmandrade, are you using windows? I faced this issue in windows. I had both python 2.7 and 3.1 installed. I uninstalled both and installed anaconda package and it seem to have fixed the issue.

**Comment by davidsmandrade** [comment]
@arunkumarchacko Exactly! I noticed it after...Thanks! :)

**Pull request merged**
